class DynamoDbTable:
    def scan(self, **kwargs: object) -> dict[str, object]: ...
    def put_item(self, *, Item: dict[str, str]) -> dict[str, object]: ...
    def get_item(self, *, Key: dict[str, str]) -> dict[str, object]: ...
    def delete_item(self, *, Key: dict[str, str]) -> dict[str, object]: ...

class DynamoDbResource:
    def Table(self, name: str) -> DynamoDbTable: ...

class ApiGatewayManagementExceptions:
    GoneException: type[Exception]

class ApiGatewayManagementClient:
    exceptions: ApiGatewayManagementExceptions
    def post_to_connection(self, *, ConnectionId: str, Data: bytes) -> object: ...

def resource(service_name: str, **kwargs: str) -> DynamoDbResource: ...
def client(service_name: str, *, endpoint_url: str) -> ApiGatewayManagementClient: ...
